### ISSUE TITLE
avoid overrinding default dist-provided files

### ISSUE THREAD

**Issue by drzraf** [sbitio/ansible-fail2ban#2]
The role itself should follow the guidelines proposed by the fail2ban author: do not erase default files.
Default fail2ban.conff and jail.conf should be kept default.
This have the advantage than upgrades get smoothly and that this role don't need to be upgraded at each major distribution upgrade. Or, state differently one could upgrade its machines without being blocked waiting for an upgrade of sbitmedia.fail2ban
Eg: in Debian Jessie, fail2ban.conf and jail.conf changed.

This patch fixes this:

``` diff
diff --git a/tasks/config.yml b/tasks/config.yml
index f5eb286..6cf6742 100644
--- a/tasks/config.yml
+++ b/tasks/config.yml
@@ -6,6 +6,7 @@
     - "fail2ban.conf.default"
   notify:
     - restart fail2ban
+  when: fail2ban_override_dist_default == true
   tags:
     - fail2ban
     - config
@@ -25,6 +26,7 @@
     - "jail.conf.default"
   notify:
     - restart fail2ban
+  when: fail2ban_override_dist_default == true
   tags:
     - fail2ban
     - config
diff --git a/vars/main.yml b/vars/main.yml
index 11b9ea3..676cf31 100644
--- a/vars/main.yml
+++ b/vars/main.yml
@@ -13,3 +13,4 @@ fail2ban_pidfile: /var/run/fail2ban/fail2ban.pid
 # Directory to store configuration parts to assemble jail.local.
 fail2ban_dir_parts: /var/tmp/ansible/fail2ban-parts

+fail2ban_override_dist_default: false
```

**Comment by jonhattan** [comment]
It's not the intention of this role to alter the default fail2ban.conf in Debian. We change it in RedHat to Debianize it, and it's a good thing.

I prefer to update the role to deploy Jessie's fail2ban.conf instead of allowing to prevent an unintended override.

**Comment by jonhattan** [comment]
Other way said, the role doesn't support debian jessie yet.

**Comment by drzraf** [comment]
But... when it comes to fail2ban, is there anything we can't do without overriding default files. I mean fail2ban seems to do a hard work to ease custom configuration without default override:

```
/etc/fail2ban/action.d
/etc/fail2ban/fail2ban.d
/etc/fail2ban/filter.d
/etc/fail2ban/jail.d
```

That would increase the ease for idempotency and could avoid all the "defer and assemble" thing which is a big drawback of this role (cf issue #3)

**Comment by jonhattan** [comment]
jail.d is new in debian jessie. I'm all for supporting it.

**Comment by drzraf** [comment]
With fail.d/ this role lost much of its usefulness.
I was able to switch to plain `template/copy/ini_file/lineinfile`
Feel free to close.
